### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by asad-awadia** [digitalocean/sample-functions-golang-helloworld#5]
Can't deploy - not even sure where this path argument needs to come from

**Comment by asad-awadia** [comment]
Once i do a basic init and then a deploy it works? but then how do i change the name?

**Comment by rabbah** [comment]
You can pass arguments to your function as query parameters (`?name=world`) or as body parameters with content type set to application/json (`{“name”=“world”}`).

**Comment by asad-awadia** [comment]
Huh? I am talking about an error at the deploy step
